import React, { Component } from 'react';
import * as d3 from 'd3';

class VisualizationBarChart extends Component {
  state = {  }

  constructor(props) {
    super(props);
    const data = [
      {name: 'Ben Cline', value: 1},
      {name: "Kendra Horn", value: 1},
      {name: "Sharice Davids", value: 1},
      {name: "Michael Guest", value: 1},
      {name: "Veronica Escobar", value: 1},
      {name: "Greg Pence", value: 1},
      {name: "Lizzie Fletcher", value: 1},
      {name: "Greg Stanton", value: 1},
      {name: "Andy Kim", value: 1},
      {name: "Sylvia Garcia", value: 1},
      {name: "Bryan Steil", value: 1},
      {name: "Van Taylor", value: 1},
      {name: "JesÃºs GarcÃ­a", value: 1},
      {name: "Kelly Armstrong", value: 1},
      {name: "Kim Schrier", value: 1},
      {name: "Daniel Meuser", value: 1},
      {name: "William Timmons", value: 1},
      {name: "Fred Keller", value: 1},
      {name: "Kevin Hern", value: 1},
      {name: "Jim Hagedorn", value: 1},
      {name: "Michael Cloud", value: 1},
      {name: "Troy Balderson", value: 1},
      {name: "Alexandria Ocasio-Cortez", value: 1},
      {name: "Jahana Hayes", value: 1},
      {name: "Madeleine Dean", value: 1},
      {name: "James Baird", value: 1},
      {name: "Kirsten E. Gillibrand", value: 1},
      {name: "Richard J. Durbin", value: 1},
      {name: "Carol Miller", value: 2},
      {name: "Ben McAdams", value: 2},
      {name: "Mikie Sherrill", value: 2},
      {name: "Katie Hill", value: 2},
      {name: "Chris Pappas", value: 2},
      {name: "Chip Roy", value: 2},
      {name: "Anthony Brindisi", value: 2},
      {name: "Jared Golden", value: 2},
      {name: "Steven Watkins", value: 2},
      {name: "Tim Burchett", value: 2},
      {name: "Michael Waltz", value: 2},
      {name: "Joe Cunningham", value: 2},
      {name: "Guy Reschenthaler", value: 2},
      {name: "Lori Trahan", value: 2},
      {name: "Matt Cartwright", value: 2},
      {name: "Mike Levin", value: 2},
      {name: "Debbie Mucarsel-Powell", value: 2},
      {name: "Ben Ray LujÃ¡n", value: 2},
      {name: "Elissa Slotkin", value: 2},
      {name: "Marsha Blackburn", value: 2},
      {name: "Mitt Romney", value: 2},
      {name: "Marco Rubio", value: 2},
      {name: "Edward J. Markey", value: 2},
      {name: "Robert Menendez", value: 2},
      {name: "Andy Levin", value: 3},
      {name: "David Cicilline", value: 3},
      {name: "Abigail Spanberger", value: 3},
      {name: "Susie Lee", value: 3},
      {name: "James Comer", value: 3},
      {name: "Katie Porter", value: 3},
      {name: "Gerald E. Connolly", value: 3},
      {name: "Rashida Tlaib", value: 3},
      {name: "Donald W. Norcross", value: 3},
      {name: "Jason Crow", value: 3},
      {name: "Diana DeGette", value: 3},
      {name: "Abby Finkenauer", value: 3},
      {name: "Antonio Delgado", value: 3},
      {name: "Susan Wild", value: 3},
      {name: "Dusty Johnson", value: 3},
      {name: "Colin Allred", value: 3},
      {name: "Dan Crenshaw", value: 3},
      {name: "Josh Harder", value: 3},
      {name: "Ilhan Omar", value: 3},
      {name: "Vicente Gonzalez", value: 3},
      {name: "TJ Cox", value: 3},
      {name: "Joni Ernst", value: 3},
      {name: "Dan Sullivan", value: 3},
      {name: "Mike Lee", value: 3},
      {name: "Tammy Baldwin", value: 3},
      {name: "Amy Klobuchar", value: 3},
      {name: "Richard Blumenthal", value: 3},
      {name: "Rand Paul", value: 3},
      {name: "Rob Portman", value: 3},
      {name: "Elizabeth Warren", value: 3},
      {name: "Bob Casey", value: 3},
      {name: "Mazie K. Hirono", value: 3},
      {name: "Christopher A. Coons", value: 3},
      {name: "Tom Udall", value: 3},
      {name: "Tim Ryan", value: 4},
      {name: "Maxine Waters", value: 4},
      {name: "Mark DeSaulnier", value: 4},
      {name: "Marcy Kaptur", value: 4},
      {name: "Mark Green", value: 4},
      {name: "Eliot L. Engel", value: 4},
      {name: "Denver Riggleman", value: 4},
      {name: "Peter T. King", value: 4},
      {name: "Elaine Luria", value: 4},
      {name: "Eric Swalwell", value: 4},
      {name: "Angie Craig", value: 4},
      {name: "Michael San Nicolas", value: 4},
      {name: "Jennifer Wexton", value: 4},
      {name: "Sean Casten", value: 4},
      {name: "Xochitl Torres Small", value: 4},
      {name: "John Lewis", value: 4},
      {name: "Cynthia Axne", value: 4},
      {name: "Adriano Espaillat", value: 4},
      {name: "Rosa DeLauro", value: 4},
      {name: "Anthony Brown", value: 4},
      {name: "Donald Beyer", value: 4},
      {name: "Raul Ruiz", value: 4},
      {name: "Gus Bilirakis", value: 4},
      {name: "Sheila Jackson Lee", value: 4},
      {name: "Jim Banks", value: 4},
      {name: "Jon Tester", value: 4},
      {name: "Bill Cassidy", value: 4},
      {name: "John Kennedy", value: 4},
      {name: "Tina Smith", value: 4},
      {name: "Mike Braun", value: 4},
      {name: "Tim Kaine", value: 4},
      {name: "Gary Peters", value: 4},
      {name: "Benjamin L. Cardin", value: 4},
      {name: "Joe Manchin III", value: 4},
      {name: "Cory Booker", value: 4},
      {name: "Jeanne Shaheen", value: 4},
      {name: "Clay Higgins", value: 5},
      {name: "Phil Roe", value: 5},
      {name: "Ted Lieu", value: 5},
      {name: "Ayanna Pressley", value: 5},
      {name: "Karen Bass", value: 5},
      {name: "Alma Adams", value: 5},
      {name: "Lucille Roybal-Allard", value: 5},
      {name: "Rob Bishop", value: 5},
      {name: "JoaquÃ­n Castro", value: 5},
      {name: "Pramila Jayapal", value: 5},
      {name: "Bobby L. Rush", value: 5},
      {name: "Tulsi Gabbard", value: 5},
      {name: "Debbie Dingell", value: 5},
      {name: "Ron Wright", value: 5},
      {name: "Al Lawson", value: 5},
      {name: "Tom O&#39;Halleran", value: 5},
      {name: "Pete Stauber", value: 5},
      {name: "Christopher H. Smith", value: 5},
      {name: "Katherine Clark", value: 5},
      {name: "Haley Stevens", value: 5},
      {name: "Greg Steube", value: 5},
      {name: "Michael McCaul", value: 5},
      {name: "Lauren Underwood", value: 5},
      {name: "Bill Flores", value: 5},
      {name: "Duncan D. Hunter", value: 5},
      {name: "Bill Keating", value: 5},
      {name: "Tom Malinowski", value: 5},
      {name: "Brian Mast", value: 5},
      {name: "A. Drew Ferguson", value: 5},
      {name: "Dean Phillips", value: 5},
      {name: "Jan Schakowsky", value: 5},
      {name: "Jackie Speier", value: 5},
      {name: "Conor Lamb", value: 5},
      {name: "Grace Meng", value: 5},
      {name: "Ami Bera", value: 5},
      {name: "Carolyn B. Maloney", value: 5},
      {name: "Judy Chu", value: 5},
      {name: "Yvette D. Clarke", value: 5},
      {name: "J. Luis Correa", value: 5},
      {name: "Mike Rounds", value: 5},
      {name: "Patty Murray", value: 5},
      {name: "Charles E. Grassley", value: 5},
      {name: "Sheldon Whitehouse", value: 5},
      {name: "Dianne Feinstein", value: 5},
      {name: "John Cornyn", value: 5},
      {name: "Ron Wyden", value: 5},
      {name: "Sherrod Brown", value: 5},
      {name: "Tammy Duckworth", value: 5},
      {name: "Jeff Merkley", value: 5},
      {name: "Margaret Hassan", value: 5},
      {name: "James Lankford", value: 5},
      {name: "Ro Khanna", value: 6},
      {name: "Dina Titus", value: 6},
      {name: "Harley Rouda", value: 6},
      {name: "Trent Kelly", value: 6},
      {name: "Bonnie Watson Coleman", value: 6},
      {name: "Doris Matsui", value: 6},
      {name: "Jerry McNerney", value: 6},
      {name: "Nancy Pelosi", value: 6},
      {name: "Scott Perry", value: 6},
      {name: "Mike Gallagher", value: 6},
      {name: "Ann McLane Kuster", value: 6},
      {name: "Brad Sherman", value: 6},
      {name: "Chris Collins", value: 6},
      {name: "Robin Kelly", value: 6},
      {name: "Francis Rooney", value: 6},
      {name: "David McKinley", value: 6},
      {name: "Jefferson Van Drew", value: 6},
      {name: "Tim Walberg", value: 6},
      {name: "Suzanne Bonamici", value: 6},
      {name: "Suzan K. DelBene", value: 6},
      {name: "Mark Takano", value: 6},
      {name: "Paul Tonko", value: 6},
      {name: "Alcee L. Hastings", value: 6},
      {name: "Eddie Bernice Johnson", value: 6},
      {name: "Elijah E. Cummings", value: 6},
      {name: "Charlie Crist", value: 6},
      {name: "Ted Deutch", value: 6},
      {name: "Dave Loebsack", value: 6},
      {name: "RaÃºl M. Grijalva", value: 6},
      {name: "Bruce Westerman", value: 6},
      {name: "Scott Peters", value: 6},
      {name: "Donna Shalala", value: 6},
      {name: "Cedric Richmond", value: 6},
      {name: "Peter Welch", value: 6},
      {name: "Julia Brownley", value: 6},
      {name: "Danny K. Davis", value: 6},
      {name: "Frank Pallone", value: 6},
      {name: "Earl Blumenauer", value: 6},
      {name: "Jacky Rosen", value: 6},
      {name: "Mary Gay Scanlon", value: 6},
      {name: "John Barrasso", value: 6},
      {name: "Debbie Stabenow", value: 6},
      {name: "John Hoeven", value: 6},
      {name: "Martin Heinrich", value: 6},
      {name: "Rick Scott", value: 6},
      {name: "Brian Schatz", value: 6},
      {name: "Patrick J. Leahy", value: 6},
      {name: "Jerry Moran", value: 6},
      {name: "Thom Tillis", value: 6},
      {name: "Christopher S. Murphy", value: 6},
      {name: "Tom Cotton", value: 6},
      {name: "Kamala Harris", value: 6},
      {name: "Jim Risch", value: 6},
      {name: "Lois Frankel", value: 7},
      {name: "Joyce Beatty", value: 7},
      {name: "Frederica Wilson", value: 7},
      {name: "Jared Huffman", value: 7},
      {name: "Kathy Castor", value: 7},
      {name: "Jerrold Nadler", value: 7},
      {name: "Robert B. Aderholt", value: 7},
      {name: "Steven J. Chabot", value: 7},
      {name: "Linda T. SÃ¡nchez", value: 7},
      {name: "Steve King", value: 7},
      {name: "Seth Moulton", value: 7},
      {name: "Scott Tipton", value: 7},
      {name: "John Garamendi", value: 7},
      {name: "Ted Budd", value: 7},
      {name: "John Katko", value: 7},
      {name: "Mark Pocan", value: 7},
      {name: "Robert C. Scott", value: 7},
      {name: "Debbie Wasserman Schultz", value: 7},
      {name: "Bennie Thompson", value: 7},
      {name: "Anna G. Eshoo", value: 7},
      {name: "Paul Gosar", value: 7},
      {name: "Brian Babin", value: 7},
      {name: "Sean Patrick Maloney", value: 7},
      {name: "Gwen Moore", value: 7},
      {name: "Susan A. Davis", value: 7},
      {name: "William Lacy Clay", value: 7},
      {name: "Brian Fitzpatrick", value: 7},
      {name: "Jimmy Panetta", value: 7},
      {name: "Barbara Lee", value: 7},
      {name: "Derek Kilmer", value: 7},
      {name: "Jenniffer GonzÃ¡lez-ColÃ³n", value: 7},
      {name: "Daniel Lipinski", value: 7},
      {name: "Debra Haaland", value: 7},
      {name: "AndrÃ© Carson", value: 7},
      {name: "Lisa Blunt Rochester", value: 7},
      {name: "Don Bacon", value: 7},
      {name: "Ron Estes", value: 7},
      {name: "Joe Wilson", value: 7},
      {name: "Eleanor Holmes Norton", value: 7},
      {name: "Joshua Hawley", value: 7},
      {name: "Martha McSally", value: 7},
      {name: "Richard M. Burr", value: 7},
      {name: "Ron Johnson", value: 7},
      {name: "Chris Van Hollen", value: 7},
      {name: "Ben Sasse", value: 7},
      {name: "Michael Bennet", value: 7},
      {name: "Mark Warner", value: 7},
      {name: "Susan Collins", value: 7},
      {name: "Lindsey Graham", value: 7},
      {name: "Cory Gardner", value: 7},
      {name: "Shelley Moore Capito", value: 7},
      {name: "John Boozman", value: 7},
      {name: "Mark Meadows", value: 8},
      {name: "Marcia L. Fudge", value: 8},
      {name: "Jodey Arrington", value: 8},
      {name: "Ruben Gallego", value: 8},
      {name: "Tony CÃ¡rdenas", value: 8},
      {name: "Zoe Lofgren", value: 8},
      {name: "Lloyd Doggett", value: 8},
      {name: "Salud Carbajal", value: 8},
      {name: "Hank Johnson", value: 8},
      {name: "Debbie Lesko", value: 8},
      {name: "Alex Mooney", value: 8},
      {name: "Albio Sires", value: 8},
      {name: "F. James Sensenbrenner", value: 8},
      {name: "Norma Torres", value: 8},
      {name: "Don Young", value: 8},
      {name: "Tom Reed", value: 8},
      {name: "Chellie Pingree", value: 8},
      {name: "Darin M. LaHood", value: 8},
      {name: "Nanette BarragÃ¡n", value: 8},
      {name: "Jim Langevin", value: 8},
      {name: "Rodney Davis", value: 8},
      {name: "Paul Mitchell", value: 8},
      {name: "Stephanie Murphy", value: 8},
      {name: "Gregorio Kilili Camacho Sablan", value: 8},
      {name: "Alan Lowenthal", value: 8},
      {name: "Jimmy Gomez", value: 8},
      {name: "Bill Foster", value: 8},
      {name: "K. Michael Conaway", value: 8},
      {name: "Max Rose", value: 8},
      {name: "Mike Johnson", value: 8},
      {name: "Joe Neguse", value: 8},
      {name: "Sean Duffy", value: 8},
      {name: "A. Donald McEachin", value: 8},
      {name: "Cathy McMorris Rodgers", value: 8},
      {name: "Kevin Cramer", value: 8},
      {name: "Todd Young", value: 8},
      {name: "Jack Reed", value: 8},
      {name: "Catherine Cortez Masto", value: 8},
      {name: "David E. Price", value: 9},
      {name: "Donald M. Payne Jr.", value: 9},
      {name: "Kevin Brady", value: 9},
      {name: "Justin Amash", value: 9},
      {name: "Ralph Norman", value: 9},
      {name: "Nita M. Lowey", value: 9},
      {name: "Denny Heck", value: 9},
      {name: "Cheri Bustos", value: 9},
      {name: "James E. Clyburn", value: 9},
      {name: "Bill Pascrell Jr.", value: 9},
      {name: "Doug Collins", value: 9},
      {name: "Joseph P. Kennedy III", value: 9},
      {name: "Filemon Vela", value: 9},
      {name: "Greg Gianforte", value: 9},
      {name: "Garret Graves", value: 9},
      {name: "Dwight Evans", value: 9},
      {name: "Jeff Fortenberry", value: 9},
      {name: "Elise Stefanik", value: 9},
      {name: "Bob Gibbs", value: 9},
      {name: "Matt Gaetz", value: 9},
      {name: "Robert E. Latta", value: 9},
      {name: "Mike Thompson", value: 9},
      {name: "Robert J. Wittman", value: 9},
      {name: "John Curtis", value: 9},
      {name: "Jody Hice", value: 9},
      {name: "Doug Jones", value: 9},
      {name: "Bernard Sanders", value: 9},
      {name: "Tim Scott", value: 9},
      {name: "David Perdue", value: 9},
      {name: "Steve Daines", value: 9},
      {name: "Thomas R. Carper", value: 9},
      {name: "Lamar Alexander", value: 9},
      {name: "Roger Wicker", value: 9},
      {name: "Angus King", value: 9},
      {name: "Lisa Murkowski", value: 9},
      {name: "Patrick T. McHenry", value: 10},
      {name: "Ron Kind", value: 10},
      {name: "Lee Zeldin", value: 10},
      {name: "Joe Morelle", value: 10},
      {name: "Trey Hollingsworth", value: 10},
      {name: "Josh Gottheimer", value: 10},
      {name: "Joe Courtney", value: 10},
      {name: "Roger Marshall", value: 10},
      {name: "Rick Allen", value: 10},
      {name: "Buddy Carter", value: 10},
      {name: "Rick Crawford", value: 10},
      {name: "Al Green", value: 10},
      {name: "Val Demings", value: 10},
      {name: "Michael R. Turner", value: 10},
      {name: "Randy Weber", value: 10},
      {name: "David Kustoff", value: 10},
      {name: "Peter A. DeFazio", value: 10},
      {name: "Pete Olson", value: 10},
      {name: "David Rouzer", value: 10},
      {name: "Lloyd Smucker", value: 10},
      {name: "Greg Walden", value: 10},
      {name: "Richard E. Neal", value: 10},
      {name: "Darren Soto", value: 10},
      {name: "Tom Emmer", value: 10},
      {name: "Larry Bucshon", value: 10},
      {name: "Glenn Grothman", value: 10},
      {name: "Thomas Suozzi", value: 10},
      {name: "Marc Veasey", value: 10},
      {name: "John Thune", value: 10},
      {name: "Deb Fischer", value: 10},
      {name: "Charles E. Schumer", value: 10},
      {name: "Cindy Hyde-Smith", value: 10},
      {name: "Ted Cruz", value: 10},
      {name: "Maria Cantwell", value: 10},
      {name: "Adam Kinzinger", value: 11},
      {name: "Tom Marino", value: 11},
      {name: "Kathleen Rice", value: 11},
      {name: "Ted Yoho", value: 11},
      {name: "Steve Stivers", value: 11},
      {name: "Kurt Schrader", value: 11},
      {name: "Stacey Plaskett", value: 11},
      {name: "Andy Biggs", value: 11},
      {name: "John Ratcliffe", value: 11},
      {name: "Mike Quigley", value: 11},
      {name: "Austin Scott", value: 11},
      {name: "John Sarbanes", value: 11},
      {name: "Michael C. Burgess", value: 11},
      {name: "Rick Larsen", value: 11},
      {name: "Terri Sewell", value: 11},
      {name: "Mark Amodei", value: 11},
      {name: "Dan Kildee", value: 11},
      {name: "David Scott", value: 11},
      {name: "Raja Krishnamoorthi", value: 11},
      {name: "Susan Brooks", value: 11},
      {name: "Will Hurd", value: 11},
      {name: "Markwayne Mullin", value: 11},
      {name: "John Moolenaar", value: 11},
      {name: "Jaime Herrera Beutler", value: 11},
      {name: "Fred Upton", value: 11},
      {name: "Juan Vargas", value: 11},
      {name: "Andy Barr", value: 11},
      {name: "Jim McGovern", value: 11},
      {name: "Michael D. Crapo", value: 11},
      {name: "Pat Roberts", value: 11},
      {name: "Patrick J. Toomey", value: 11},
      {name: "Johnny Isakson", value: 11},
      {name: "Jamie Raskin", value: 12},
      {name: "Brad Schneider", value: 12},
      {name: "Glenn Thompson", value: 12},
      {name: "Brad Wenstrup", value: 12},
      {name: "Devin Nunes", value: 12},
      {name: "Adrian Smith", value: 12},
      {name: "Pete Aguilar", value: 12},
      {name: "Tom Rice", value: 12},
      {name: "Vicky Hartzler", value: 12},
      {name: "Emanuel Cleaver II", value: 12},
      {name: "Mike Bost", value: 12},
      {name: "John Rutherford", value: 12},
      {name: "Brendan Boyle", value: 12},
      {name: "Mike Simpson", value: 12},
      {name: "Collin C. Peterson", value: 12},
      {name: "Virginia Foxx", value: 12},
      {name: "Doug LaMalfa", value: 12},
      {name: "Dave Joyce", value: 12},
      {name: "Mark Walker", value: 12},
      {name: "Brian Higgins", value: 12},
      {name: "Jim Himes", value: 12},
      {name: "Kyrsten Sinema", value: 12},
      {name: "French Hill", value: 12},
      {name: "Jason Smith", value: 12},
      {name: "Mike Kelly", value: 12},
      {name: "Hakeem Jeffries", value: 12},
      {name: "Ken Calvert", value: 12},
      {name: "James M. Inhofe", value: 12},
      {name: "Kevin McCarthy", value: 13},
      {name: "Steve Scalise", value: 13},
      {name: "Barry Loudermilk", value: 13},
      {name: "Kay Granger", value: 13},
      {name: "Gregory W. Meeks", value: 13},
      {name: "G. K. Butterfield", value: 13},
      {name: "Warren Davidson", value: 13},
      {name: "Tom McClintock", value: 13},
      {name: "Steven Palazzo", value: 13},
      {name: "Betty McCollum", value: 13},
      {name: "Bradley Byrne", value: 13},
      {name: "Vern Buchanan", value: 13},
      {name: "Scott DesJarlais", value: 13},
      {name: "Bill Posey", value: 13},
      {name: "Brett Guthrie", value: 13},
      {name: "Blaine Luetkemeyer", value: 13},
      {name: "Chris Stewart", value: 13},
      {name: "Paul Cook", value: 13},
      {name: "Mike Doyle", value: 13},
      {name: "Billy Long", value: 13},
      {name: "John B. Larson", value: 13},
      {name: "Jack Bergman", value: 13},
      {name: "Kenny Marchant", value: 13},
      {name: "David Schweikert", value: 13},
      {name: "Steve Cohen", value: 13},
      {name: "Liz Cheney", value: 13},
      {name: "Ann Wagner", value: 13},
      {name: "Adam Smith", value: 13},
      {name: "Mario Diaz-Balart", value: 13},
      {name: "Steven Horsford", value: 13},
      {name: "Gary Palmer", value: 13},
      {name: "Dan Newhouse", value: 13},
      {name: "Michael B. Enzi", value: 13},
      {name: "Roy Blunt", value: 13},
      {name: "Morgan Griffith", value: 14},
      {name: "Jackie Walorski", value: 14},
      {name: "Harold Rogers", value: 14},
      {name: "John Yarmuth", value: 14},
      {name: "Neal Dunn", value: 14},
      {name: "Stephen F. Lynch", value: 14},
      {name: "John Carter", value: 14},
      {name: "Grace F. Napolitano", value: 14},
      {name: "Doug Lamborn", value: 14},
      {name: "Amata Coleman Radewagen", value: 14},
      {name: "Peter J. Visclosky", value: 14},
      {name: "Ken Buck", value: 14},
      {name: "Daniel Webster", value: 14},
      {name: "Ed Perlmutter", value: 14},
      {name: "Steny H. Hoyer", value: 15},
      {name: "Ed Case", value: 15},
      {name: "Mo Brooks", value: 15},
      {name: "Walter B. Jones", value: 15},
      {name: "Martha Roby", value: 15},
      {name: "George Holding", value: 15},
      {name: "Bill Johnson", value: 15},
      {name: "Adam B. Schiff", value: 15},
      {name: "Brenda Lawrence", value: 15},
      {name: "Frank D. Lucas", value: 15},
      {name: "Bill Huizenga", value: 15},
      {name: "Mike D. Rogers", value: 15},
      {name: "Chuck Fleischmann", value: 15},
      {name: "JosÃ© E. Serrano", value: 15},
      {name: "Richard Hudson", value: 15},
      {name: "John Shimkus", value: 15},
      {name: "Thomas Massie", value: 15},
      {name: "Tom Cole", value: 15},
      {name: "Sanford D. Bishop Jr.", value: 15},
      {name: "Jim Jordan", value: 16},
      {name: "Tom Graves", value: 16},
      {name: "Henry Cuellar", value: 16},
      {name: "Ralph Abraham", value: 16},
      {name: "Jeffrey Duncan", value: 16},
      {name: "Louie Gohmert", value: 16},
      {name: "C.A. Dutch Ruppersberger", value: 16},
      {name: "Mitch McConnell", value: 16},
      {name: "Richard C. Shelby", value: 16},
      {name: "Steve Womack", value: 17},
      {name: "William M. Thornberry", value: 17},
      {name: "Ann Kirkpatrick", value: 17},
      {name: "Roger Williams", value: 17},
      {name: "Sam Graves", value: 17},
      {name: "Jim Costa", value: 17},
      {name: "Jim Cooper", value: 18},
      {name: "Andy Harris", value: 18},
      {name: "Rob Woodall", value: 18},
    ]
    this.state = {
      data: data,
    }
  }

  componentDidMount() {
    const data = this.state.data.sort(function (a, b) {
        return d3.ascending(a.value, b.value);
    });

    //set up svg using margin conventions - we'll need plenty of room on the left for labels
    var margin = {
        top: 15,
        right: 25,
        bottom: 15,
        left: 165
    };

    var width = 960 - margin.left - margin.right,
        height = 8000 - margin.top - margin.bottom;

    var svg = d3.select("#graphic").append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
        .append("g")
        .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

    var x = d3.scaleLinear()
        .range([0, width])
        .domain([0, d3.max(data, function (d) {
            return d.value;
        })]);

    var y = d3.scaleBand()
        .rangeRound([height, 0])
        .padding(0.1)
        .domain(data.map(function (d) {
            return d.name;
        }));

    //make y axis to show bar names
    var yAxis = d3.axisLeft(y)
        // .scale(y)
        //no tick marks
        .tickSize(0)
        // .orient("left");

    var gy = svg.append("g")
        .attr("class", "y axis")
        .call(yAxis)

    var bars = svg.selectAll(".bar")
        .data(data)
        .enter()
        .append("g")

    //append rects
    bars.append("rect")
        .attr("class", "bar")
        .attr("y", function (d) {
            return y(d.name);
        })
        .attr("height", y.bandwidth())
        .attr("x", 0)
        .attr("width", function (d) {
            return x(d.value);
        });

    //add a value label to the right of each bar
    bars.append("text")
        .attr("class", "label")
        //y position of the label is halfway down the bar
        .attr("y", function (d) {
            return y(d.name) + y.bandwidth() / 2 + 4;
        })
        //x position is 3 pixels to the right of the bar
        .attr("x", function (d) {
            return x(d.value) + 3;
        })
        .text(function (d) {
            return d.value;
        });
  }

  render() { 
    return (
      <div className="visualization-bar-chart">
        <div id="graphic"></div>
      </div>
    );
  }
}
 
export default VisualizationBarChart;